[build]
  command = "yarn generate"
  functions = "functions"
  publish = "dist"

[[plugins]]
  package = "netlify-plugin-github-dispatch"
  [plugins.inputs]
    owner = "bahmutov"
    repo = "ecommerce-netlify"
    workflow = ".github/workflows/e2e.yml"
